apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dgwm6etpm-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:75c56c5c4c95ca225c0d13b09bbea46ccde3a0d7@sha256:59aa304c7585324cbf48b6c315de98c4e6c663d9b68a78d724cbf82ab0841f6c
          name: container-image
